name: Everette
favicon: null
layout_spectrum: 0.7078853
typography_spectrum: 0.4444444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#9d9d9d'
    - '#4c4c4c'
    - '#cbcbcb'
    - '#f3f3f3'
  brandStrength: 0.9235132
  lightness: 1
  saturation: 0.5143369
  rhythmicContrast: 0
purpose: []
