layout_spectrum: 0.7078853
color:
  saturation: 0.5143369
  brandStrength: 0.9235132
  lightness: 1
  rhythmicContrast: 0
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.4444444
name: Everette
